/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Controlador.EmpleadoControlador;
import Modelo.Empleado;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author COMPHP
 */
public class VistaEmpleados extends javax.swing.JPanel {
     private final EmpleadoControlador empleadoControlador;
    private Integer idEmpleadoSeleccionado = null;
    /**
     * Creates new form VistaEmpleado
     */
    public VistaEmpleados() {
        initComponents();
        this.empleadoControlador= new EmpleadoControlador();
        cargarDatosTabla();
    }
    
    public void cargarDatosTabla() {
        //Obtener todas las categorias del controlador
        List<Empleado> empleados = empleadoControlador.obtenerTodosEmpleados();
        if (empleados != null) {
            // obtener el modelo existente de la tabla
            DefaultTableModel model = (DefaultTableModel) tablaEmpleado.getModel();
            model.setRowCount(0);
            //llenar las filas con los datos de categorias  
            for (Empleado cli : empleados) {
                Object[] row = {
                    cli.getIdEmpleado(),
                    cli.getPrimerNombre(),
                    cli.getSegundoNombre(),
                    cli.getPrimerApellido(),
                    cli.getSegundoApellido(),
                    cli.getCelular(),
                    cli.getCargo(),
                    cli.getFechaContratacion()
                };
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabel1 = new javax.swing.JLabel();
        textprimer_nombre = new javax.swing.JTextField();
        jlabel2 = new javax.swing.JLabel();
        textsegundo_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textprimer_apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textsegundo_apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textcelular = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textcargo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        BuscarEmpleado = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        textfecha_contratacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleado = new javax.swing.JTable();

        jlabel1.setText("primer_nombre");

        textprimer_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textprimer_nombreActionPerformed(evt);
            }
        });

        jlabel2.setText("segundo_nombre");

        textsegundo_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textsegundo_nombreActionPerformed(evt);
            }
        });

        jLabel3.setText("primer_apellido");

        textprimer_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textprimer_apellidoActionPerformed(evt);
            }
        });

        jLabel4.setText("segundo_apellido");

        textsegundo_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textsegundo_apellidoActionPerformed(evt);
            }
        });

        jLabel5.setText("celular");

        textcelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcelularActionPerformed(evt);
            }
        });

        jLabel6.setText("cargo");

        textcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcargoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionbtnGuardar(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        BuscarEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBuscarEmpleadoKeyTyped(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionbtnEliminar(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionbtnActualizar(evt);
            }
        });

        textfecha_contratacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfecha_contratacionActionPerformed(evt);
            }
        });

        jLabel7.setText("fecha_contratacion");

        tablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idEmpleado", "primer_nombre", "segundo_nombre", "primer_apellido", "segundo_apellido", "celular", "cargo", "fecha_contratacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textprimer_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textsegundo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textprimer_apellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textsegundo_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textfecha_contratacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textprimer_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textsegundo_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textsegundo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textprimer_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(textfecha_contratacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(textcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textprimer_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textprimer_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textprimer_nombreActionPerformed

    private void textsegundo_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textsegundo_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textsegundo_nombreActionPerformed

    private void textprimer_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textprimer_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textprimer_apellidoActionPerformed

    private void textsegundo_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textsegundo_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textsegundo_apellidoActionPerformed

    private void textcelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcelularActionPerformed

    private void textcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcargoActionPerformed

    private void accionbtnGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionbtnGuardar
        String primerNombre = textprimer_nombre.getText().trim();
        String segundoNombre = textsegundo_nombre.getText().trim();
        String primerApellido = textprimer_apellido.getText().trim();
        String segundoApellido = textsegundo_apellido.getText().trim();
        String celular = textcelular.getText().trim();
        String cargo = textcargo.getText().trim();
        String fechaContratacionStr = textfecha_contratacion.getText().trim();

        if (!primerNombre.isEmpty() && !primerApellido.isEmpty() && !celular.isEmpty() && 
            !cargo.isEmpty() && !fechaContratacionStr.isEmpty()) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                java.util.Date parsedDate = sdf.parse(fechaContratacionStr);
                Date fechaContratacion = new Date(parsedDate.getTime());
                
                empleadoControlador.crearEmpleado(primerNombre, segundoNombre, primerApellido, 
                    segundoApellido, celular, cargo, fechaContratacion);
                cargarDatosTabla();
                
                // Clear form
                textprimer_nombre.setText("");
                textsegundo_nombre.setText("");
                textprimer_apellido.setText("");
                textsegundo_apellido.setText("");
                textcelular.setText("");
                textcargo.setText("");
                textfecha_contratacion.setText("");
                
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use yyyy-MM-dd.", 
                    "Error", JOptionPane.ERROR_MESSAGE); 
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, llene los campos obligatorios.", 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionbtnGuardar

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    private void accionbtnEliminar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionbtnEliminar
       int filaSeleccionada = tablaEmpleado.getSelectedRow();
        if (filaSeleccionada != -1) {
            int idEmpleado = (int) tablaEmpleado.getValueAt(filaSeleccionada, 0);
            empleadoControlador.eliminarEmpleado(idEmpleado);
            cargarDatosTabla();
            idEmpleadoSeleccionado = null;
            
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.", 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_accionbtnEliminar

    private void accionbtnActualizar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionbtnActualizar
        String primerNombre = textprimer_nombre.getText().trim();
        String segundoNombre = textsegundo_nombre.getText().trim();
        String primerApellido = textprimer_apellido.getText().trim();
        String segundoApellido = textsegundo_apellido.getText().trim();
        String celular = textcelular.getText().trim();
        String cargo = textcargo.getText().trim();
        String fechaContratacionStr = textfecha_contratacion.getText().trim();

        if (idEmpleadoSeleccionado != null && !primerNombre.isEmpty() && !primerApellido.isEmpty() && 
            !celular.isEmpty() && !cargo.isEmpty() && !fechaContratacionStr.isEmpty()) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                java.util.Date parsedDate = sdf.parse(fechaContratacionStr);
                Date fechaContratacion = new Date(parsedDate.getTime());
                
                empleadoControlador.actualizarEmpleado(idEmpleadoSeleccionado, primerNombre, segundoNombre, 
                    primerApellido, segundoApellido, celular, cargo, fechaContratacion);
                cargarDatosTabla();
                
               
                textprimer_nombre.setText("");
                textsegundo_nombre.setText("");
                textprimer_apellido.setText("");
                textprimer_apellido.setText("");
                textsegundo_apellido.setText("");
                textcelular.setText("");
                textcargo.setText("");
                textfecha_contratacion.setText("");
                idEmpleadoSeleccionado = null;
                
                btnEliminar.setEnabled(true);
                btnGuardar.setEnabled(true);
                
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use yyyy-MM-dd.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, llene los campos obligatorios.", 
                "Error", JOptionPane.ERROR_MESSAGE);
        }                               

    }//GEN-LAST:event_accionbtnActualizar

    private void textfecha_contratacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfecha_contratacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfecha_contratacionActionPerformed

    private void tablaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseClicked
        if (evt.getClickCount() == 2) {
            int filaSeleccionada = tablaEmpleado.getSelectedRow();
            if (filaSeleccionada != -1) {
                idEmpleadoSeleccionado = (int) tablaEmpleado.getValueAt(filaSeleccionada, 0);
                String primerNombre = (String) tablaEmpleado.getValueAt(filaSeleccionada, 1);
                String segundoNombre = (String) tablaEmpleado.getValueAt(filaSeleccionada, 2);
                String primerApellido = (String) tablaEmpleado.getValueAt(filaSeleccionada, 3);
                String segundoApellido = (String) tablaEmpleado.getValueAt(filaSeleccionada, 4);
                String celular = (String) tablaEmpleado.getValueAt(filaSeleccionada, 5);
                String cargo = (String) tablaEmpleado.getValueAt(filaSeleccionada, 6);
                Date fechaContratacion = (Date) tablaEmpleado.getValueAt(filaSeleccionada, 7);

                textprimer_nombre.setText(primerNombre);
                textsegundo_nombre.setText(segundoNombre != null ? segundoNombre : "");
                textprimer_apellido.setText(primerApellido);
                textsegundo_apellido.setText(segundoApellido != null ? segundoApellido : "");
                textcelular.setText(celular);
                textcargo.setText(cargo);
                textfecha_contratacion.setText(fechaContratacion != null ? 
                    new SimpleDateFormat("yyyy-MM-dd").format(fechaContratacion) : "");

                btnEliminar.setEnabled(false);
                btnGuardar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tablaClienteMouseClicked

    private void textBuscarEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarEmpleadoKeyTyped
       String textoBusqueda = BuscarEmpleado.getText().trim().toLowerCase();
        List<Empleado> empleados = empleadoControlador.obtenerTodosEmpleados();
        
        DefaultTableModel modelo = (DefaultTableModel) tablaEmpleado.getModel();
        modelo.setRowCount(0);
        
        if (empleados != null) {
            for (Empleado emp : empleados) {
                if (textoBusqueda.isEmpty() || 
                    emp.getPrimerNombre().toLowerCase().contains(textoBusqueda) ||
                    (emp.getSegundoNombre() != null && emp.getSegundoNombre().toLowerCase().contains(textoBusqueda)) ||
                    emp.getPrimerApellido().toLowerCase().contains(textoBusqueda) ||
                    (emp.getSegundoApellido() != null && emp.getSegundoApellido().toLowerCase().contains(textoBusqueda)) ||
                    emp.getCelular().toLowerCase().contains(textoBusqueda) ||
                    emp.getCargo().toLowerCase().contains(textoBusqueda)) {
                    Object[] fila = {
                        emp.getIdEmpleado(),
                        emp.getPrimerNombre(),
                        emp.getSegundoNombre(),
                        emp.getPrimerApellido(),
                        emp.getSegundoApellido(),
                        emp.getCelular(),
                        emp.getCargo(),
                        emp.getFechaContratacion()
                    };
                    modelo.addRow(fila);
                }
           
            }
        }
    }//GEN-LAST:event_textBuscarEmpleadoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField BuscarEmpleado;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JTable tablaEmpleado;
    private javax.swing.JTextField textcargo;
    private javax.swing.JTextField textcelular;
    private javax.swing.JTextField textfecha_contratacion;
    private javax.swing.JTextField textprimer_apellido;
    private javax.swing.JTextField textprimer_nombre;
    private javax.swing.JTextField textsegundo_apellido;
    private javax.swing.JTextField textsegundo_nombre;
    // End of variables declaration//GEN-END:variables
}
